[package]
name = "confirmation"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
gio = "0.20.11"
gtk4 = { version = "0.9.6", features = ["v4_12"] }
gtk4-layer-shell = "0.4.0"
